# Generated by Django 5.0.3 on 2024-04-19 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_comment_rating_alter_post_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
